https://docs.google.com/document/d/1rDFpf61GTPv-lzxGsA5jyRgbBnsEJOt9xJlXQBQhh54/edit?tab=t.0

In [4]:
import numpy as np

In [6]:
#1
one_d=np.array([1,2,3,4])

two_d=np.array([[1,2,3,4],
                [5,6,7,8]])

three_d=np.array([[[1,2,3,4],
                   [5,6,7,8]],

                  [[9,10,11,12],
                   [13,14,15,16]]])
print(one_d.ndim)
print(two_d.ndim)
print(three_d.ndim)

print(one_d.shape)
print(two_d.shape)
print(three_d.shape)

1
2
3
(4,)
(2, 4)
(2, 2, 4)


In [10]:
#2
z=np.zeros((3,3))
o=np.ones((2,5))
f=np.full(5,7)
print(z)
print(o)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[7 7 7 7 7]


In [11]:
#3
evn=np.arange(10,50,2)
evn

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [23]:
#4
arr=np.arange(0,16).reshape(4,4)
f_r=arr[:1,:]
l_c=arr[:,3:]
cen=arr[1:3,1:3]
print(f_r)
print(l_c)
print(cen)

[[0 1 2 3]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 5  6]
 [ 9 10]]


In [25]:
#5
arr1=np.random.randint(1,10,9).reshape(3,3)
arr2=np.array([1,2,3])
print(arr1)
print(arr1+arr2)


[[2 2 3]
 [4 9 2]
 [9 5 5]]
[[ 3  4  6]
 [ 5 11  5]
 [10  7  8]]


In [26]:
#6
a=np.random.randint(1,10,9).reshape(3,3)
b=np.random.randint(11,20,9).reshape(3,3)
print((a+b)/2)
print(a**2+b**2)

[[10.5 10.  10. ]
 [10.  12.   8.5]
 [10.5 10.   8.5]]
[[225 362 328]
 [298 306 185]
 [225 298 257]]
