In [1]:
import numpy as np
arr= np.random.randint(1,100,size=(10,5))

In [2]:
arr.shape

(10, 5)

In [3]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[67, 86,  8, 70, 73, 93, 51, 40, 78, 96],
       [42, 37, 59, 99, 89, 72, 46, 57, 26, 91],
       [74, 63, 71, 86, 14, 68, 10, 81, 25, 50],
       [38, 48, 26, 96, 66, 90, 58, 97, 97, 50],
       [31, 17, 34, 33, 33, 20, 91, 77, 22, 70]])

**flatten** -->convert nd in row wise 1d

**ravel** --> convert nd in column wise 1d

In [4]:
flatten = b.flatten()
print(flatten.ndim)
print(flatten)

column_wise_flattening = np.ravel(b,order= 'F')

print(column_wise_flattening)

1
[67 86  8 70 73 93 51 40 78 96 42 37 59 99 89 72 46 57 26 91 74 63 71 86
 14 68 10 81 25 50 38 48 26 96 66 90 58 97 97 50 31 17 34 33 33 20 91 77
 22 70]
[67 42 74 38 31 86 37 63 48 17  8 59 71 26 34 70 99 86 96 33 73 89 14 66
 33 93 72 68 90 20 51 46 10 58 91 40 57 81 97 77 78 26 25 97 22 96 91 50
 50 70]


In [5]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))
print(a)
print(b)

[[4 9 9]
 [4 8 2]]
[[21 27 24]
 [26 25 22]]


**concatenate**

In [6]:
con_row = np.concatenate((a,b),axis=0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise

print(con_col)

[[ 4  9  9]
 [ 4  8  2]
 [21 27 24]
 [26 25 22]]
[[ 4  9  9 21 27 24]
 [ 4  8  2 26 25 22]]


In [7]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

**transpose**

In [10]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


**array split**

In [11]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3)

[5 6 1 6 5 1 4 2 7 1]
[array([5, 6, 1, 6]), array([5, 1, 4]), array([2, 7, 1])]


ValueError: array split does not result in an equal division

#arithmetic operator and mathematical functions

In [12]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [13]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [14]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [16]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumsum(x)
print(cumul)

134
[ 10  18  34 134]


In [17]:

#broadcasting

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2

#rulings = columns er size and vector er size same hote hobe

matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2

vector = np.array([1,2,3])
result = matrix + vector
print(result)


[[11 22 33]
 [31 42 53]]


#Logical Function

In [18]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


#Sorting

In [19]:
#inplace--> change the main file
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [20]:
# copy sorting--> maiN FILE THIK THAKE
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [21]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


#Searching

In [22]:
print(x)

[ 10   8  16 100]


In [23]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [24]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [25]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [26]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


#counting in ndarray

In [27]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[84  8 75  5 23 89 51 52 35  8 56 30 91 70 44 47  5 49 89 73  6 63 36 46
 43 29 98 19 73 18  1 77  6 80 91 69 68 42 99 60 70 73 79 37 67 90 71 63
 79 83 49 34 93 38  6 47 84 49 84 25 92 91  4 17 28 96 93 15 22 26 98 49
 98 49  3 35 93 99 17  8  7 27 31 41 13 62 34 23 96 69  5 68  1 29 75 80
 76 57 65 47]


In [28]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

0


#statistical function

In [29]:

#data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)

FileNotFoundError: student_scores.csv not found.

In [30]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

NameError: name 'data' is not defined

In [31]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


#linear algebra

In [32]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))

[[ 58  64]
 [139 154]]
17


In [33]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

0.0
2


In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]


#Problem in Module

In [ ]:
#https://www.deep-ml.com/problems/4
import numpy as np
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
    mat =np.array(matrix)
    if mode=="row":
        means=np.mean(mat,axis=1).tolist()
    else:
        means=np.mean(mat,axis=0).tolist()

	return means

In [35]:
#https://www.deep-ml.com/problems/1

import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.
    a=np.array(a)
    b=np.array(b)
    shape_a=a.shape
    if shape_a[1]!=b.size:
        return -1

    dot=np.dot(a,b).tolist()
    return dot
	pass

#quiz explaination

https://docs.google.com/document/d/13InSqgBr0Fys1SGQ7Ynxbf3FCcPUaf4bsQ_U_vIyjJU/edit?tab=t.0

#Practice Problem



https://docs.google.com/document/d/1s2boyWYFGibJX2UmILiWjn-zj0qbkKktNN9kmahlNMQ/edit?tab=t.0

In [ ]:
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    a=np.array(a)
    b=a.T
	return b