In [2]:
arr = [1,2,3]

print( arr * 5 )

arr = [ x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:

import numpy as np

arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


**Nd Array**

n dimensional array

In [4]:
import numpy as np
#1d array
arr1 = np.array([1,2,3])
#2d Array
arr2=np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]

               ])

#3d array
arr3=np.array([

               [[1,2,3],
                [3,4,5]
               ],
               [
                   [5,6,7],
                   [9,10,11]
               ]
])
print(arr1)
print(type(arr1))


[1 2 3]
<class 'numpy.ndarray'>


#Array attribute

In [5]:
#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#datatype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(3,)
(4, 5)
(2, 2, 3)
int64
int64
int64
3
20
12


**Datatype**

In [6]:
arr=np.array([1,2,3])
print(arr.dtype)

arr=np.array([1.4,2.4,3.4])
print(arr.dtype)

#upcasting
arr=np.array([1,2,3.6])
print(arr.dtype)

#upcasted ass string
arr=np.array([1,2,3.6,'hello'])
print(arr.dtype)
arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)


int64
float64
float64
<U32
<U32


**selecting a data type for an array**

In [7]:
arr = np.array([1,2,30],dtype=np.int8) #-127 to 127
print(arr.dtype)
print(arr)

arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)
arr = arr.astype(np.int32)
print(arr.dtype)

#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int8
[ 1  2 30]
int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

#ndarray creation from existing data

In [8]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)

mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)

matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


#tuple

In [9]:


tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


#set

In [10]:


st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


# dictionary


In [11]:

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [13]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [14]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [16]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


#Creating ndarray from scratch

In [17]:
# np.zeros

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)


In [18]:
#np.ones

arr = np.ones((3,4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [19]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [21]:
#np.full

arr = np.full((4,3),np.inf)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(2, 2, 3)
float64


#array creation with random values

In [24]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.66272173 0.70378396 0.17680061]
 [0.15227476 0.51926392 0.08211612]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [25]:

# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[6 2 7]
 [9 5 5]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [26]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[66.17768496 79.11933972 51.48169529 75.15665754]
  [57.21165259 73.97074808 51.83519324 97.3672746 ]
  [73.49415029 51.62267849 61.56142307 86.20243321]]

 [[95.90592363 84.36990553 63.86447304 88.11421754]
  [65.60554546 85.88368854 53.39851566 77.02357584]
  [60.22817174 51.78697836 52.51795891 59.86056694]]

 [[63.676902   95.74033014 89.18317557 72.74502969]
  [51.48912339 88.18353771 72.71784682 76.94494034]
  [91.89340818 55.68031742 64.35915503 83.54964649]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


#array creation with range functions

In [27]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [28]:

# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [29]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


#creating matrix for Linear algebra

In [30]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [31]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#indexing and slicing

In [32]:

#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)

[1 2 3]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [34]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [41]:
#2d slicing
# # arr[ row_start : row_end : step , column_start : column_end : step ]

# # print(arr2)

# #getting a row

# row_0 = arr2[0:1 ,]

# row_1= arr2[1: , ]

# # print(row_0)
# # print(row_1)


# #getting a column

# col_0 = arr2[:: ,0:1]
# col_1 = arr2[::,1:2]

# print(col_0)
# print(col_1)

# #getting a portion

print(arr2)
portion = arr2[:: , 0:2]

print(portion)

[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


#Advanced Indexing

In [36]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [42]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr2>1])
arr2[arr2>2] = 0

print(arr2)

[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]
[2 8]
[  2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20]
[[1 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [38]:
print(arr2)

[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [39]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 5  6  7]
  [ 9 10 11]]]
1
2
3
3
4
5
5
6
7
9
10
11


#quiz explaination



https://docs.google.com/document/d/1D7ivdTJ6s7NjTZi-TP4P8pvSo-MpOOxbjfqTUBIdT-o/edit?tab=t.0#heading=h.8qalwvmka0tp

#Practice Problems

https://docs.google.com/document/d/17mv1g8UmPDyCMtSERnE0G4WCV82xeeKc7DvKRId9jXU/edit?tab=t.0

In [43]:
#1
import numpy as np

# given list of temperatures in Celsius
celsius = [0, 20, 37, 100, -10]

# create a NumPy array
c = np.array(celsius)

# convert Celsius to Fahrenheit
f = c * 1.8 + 32

# print the Fahrenheit array
print("Fahrenheit temperatures:", f)


Fahrenheit temperatures: [ 32.   68.   98.6 212.   14. ]


In [45]:
#2
import numpy as np

lap_times = [75, 80, 78, 82, 76]

times = np.array(lap_times)

print("Shape:", times.shape)
print("Size:", times.size)
print("Data type:", times.dtype)

minutes = times / 60

print("Lap times in minutes:", minutes)


Shape: (5,)
Size: 5
Data type: int64
Lap times in minutes: [1.25       1.33333333 1.3        1.36666667 1.26666667]
