**email address : rifatrizviofficial001@gmail.com**

https://phitron.io/ml-01/assignment/ml-01-mid-term

In [33]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


#Answer to Q1

In [34]:

age=np.array(ages)
salary=np.array(salaries)
print(age)
print(salary)

print("Age Info:\n")
print(age.dtype)
print(age.ndim)
print(age.shape)
print(age.size)

print("Salary Info:\n")
print(salary.dtype)
print(salary.ndim)
print(salary.shape)
print(salary.size)


[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
Age Info:

int64
1
(10,)
10
Salary Info:

int64
1
(10,)
10


#Answer to Q2

In [35]:
h_sal=np.max(salary)
l_sal=np.min(salary)
avg_sal=np.mean(salary)
avg_age=np.mean(age)

print("Highest Salary:",h_sal)
print("Lowest Salary:",l_sal)
print("Average Salary:",avg_sal)
print("Average Age:",avg_age)

Highest Salary: 89735
Lowest Salary: 30769
Average Salary: 57446.9
Average Age: 38.5


#Answer to Q3

In [36]:
age_over_30=age[age>30]
cnt_over_30=np.sum(age>30)

print(age_over_30)
print(cnt_over_30)

[56 46 32 38 56 36 40]
7


#Answer to Q4

In [37]:
updt_age=age+5
print(updt_age)

[61 51 37 30 43 61 41 45 33 33]


#Answer to Q5

In [38]:
tot_sal=np.sum(salary)
diff_sal=np.max(salary)-np.min(salary)
print(tot_sal)
print(diff_sal)

574469
58966


#Answer to Q6

In [39]:
df=pd.read_csv("employees.csv")
print(df.head())
print(df.info())
print(df.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


#Answer to Q7

In [40]:
slctd_col=df.loc[:,['id','age','salary']]
print(slctd_col)
print(slctd_col.tail(3))

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311
   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


#Answer to Q8

In [41]:
it_employee=df[df['dept']=='IT']
print(it_employee)
print(it_employee.shape[0])

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
3


#Answer to Q9

In [42]:
sort_df = df.sort_values(['salary'],ascending=False)

top_3 = sort_df.loc[:,['dept','age','salary']].head(3)
print(sort_df)

print(top_3)

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR
1   2   46   74131       IT
3   4   25   71090       IT
2   3   32   46023  Finance
9  10   28   35311       HR
8   9   28   32433    Sales
4   5   38   31685       HR
5   6   56   30769    Sales
      dept  age  salary
6  Finance   36   89735
7       IT   40   86101
0       HR   56   77191


#Answer to Q10


In [43]:
df.loc[df['salary']>80000 ,'salary']=80000
new_avg_sal=df['salary'].mean()
print(new_avg_sal)

55863.3
