# version 1

In [1]:
import torch
import torch.nn as nn

In [2]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     self.linear = nn.Linear(num_features,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear(features)
#     out = self.sigmoid(out)

#     return out

# Version 2

In [3]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     #layer 1

#     self.linear1 = nn.Linear(num_features,3)
#     self.relu = nn.ReLU()

#     #layer 2
#     self.linear2 = nn.Linear(3,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear1(features)
#     out = self.relu(out)

#     out = self.linear2(out)
#     out = self.sigmoid(out)

#     return out

In [4]:
# Version 3


class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU() ,   #index 1
        nn.Linear(3,1),  #index 2
        nn.Sigmoid()  #index 3

    )

  def forward(self,features):
    out = self.network(features)

    return out

In [5]:
# Create dataset

features = torch.rand(10,5)

In [6]:
features

tensor([[0.3036, 0.0062, 0.1487, 0.8567, 0.6292],
        [0.8378, 0.3668, 0.1121, 0.2912, 0.4547],
        [0.1301, 0.1311, 0.7065, 0.3143, 0.9428],
        [0.0605, 0.8100, 0.5661, 0.2885, 0.1740],
        [0.8689, 0.8543, 0.0256, 0.1182, 0.2085],
        [0.5370, 0.3485, 0.6872, 0.2001, 0.3076],
        [0.2261, 0.8459, 0.6283, 0.7414, 0.3347],
        [0.4488, 0.4327, 0.8277, 0.1438, 0.5137],
        [0.5865, 0.4103, 0.7924, 0.0779, 0.9158],
        [0.1367, 0.8842, 0.0753, 0.9200, 0.2116]])

In [7]:
features.shape[1]

5

In [8]:
#create model

model = Model(features.shape[1])

In [9]:
#calling model for forward pass
# model.forward(features)

model(features)

tensor([[0.4016],
        [0.3914],
        [0.4133],
        [0.3874],
        [0.3997],
        [0.3949],
        [0.3869],
        [0.3998],
        [0.4089],
        [0.3793]], grad_fn=<SigmoidBackward0>)

In [17]:
#show model weights
model.network[2].weight

Parameter containing:
tensor([[-0.3719,  0.3100, -0.1208]], requires_grad=True)

In [14]:
# visualize

!pip install torchinfo

In [15]:
from torchinfo import summary

summary( model,input_size = (10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Extra

In [11]:
# Base Class
class Rectangle:
    def __init__(self, length, width):
        print("Rectangle constructor called")
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width


# Child Class (Square inherits Rectangle)
class Square(Rectangle):
    def __init__(self, side):
        print("Square constructor called")
        super().__init__(side, side)   # Calls Rectangle constructor

    def square_info(self):
        return f"Square area: {self.area()}"


# Child Class (Cube inherits Square)
class Cube(Square):
    def __init__(self, side):
        print("Cube constructor called")
        super().__init__(side)   # Calls Square constructor

    def volume(self):
        return self.length ** 3


# Create Object
cube = Cube(4)

print("Area:", cube.area())
print("Volume:", cube.volume())

Cube constructor called
Square constructor called
Rectangle constructor called
Area: 16
Volume: 64
